### ISSUE TITLE
Installations/Asuführungs Anleitung

### ISSUE THREAD

**Issue by Soliver84** [FritzTools/FRED#1]
Hallo

Warum gibt es keine Installations Ausführungsanleitung?

Oder gleich eine EXE?

Grüße
Soliver84

**Comment by Bizarrus** [comment]
Hallo @Soliver84,

dir scheint GitHub nicht geläufig zu sein, oder? Denn eine Ausführbare Anwendung findet sich meist immer auf GitHub in dem Navigationspunkt **Releases**:

https://github.com/FritzTools/FRED/releases

Auch befindet sich die Software noch **in der Entwicklung**, daher wirst du mit dem Pre-Alpha Release nicht viel anfangen können.

Was noch alles auf der ToDo-Liste steht, findest du hier, wie bereits auf der Hauptseite beschrieben: https://github.com/orgs/FritzTools/projects/1

Mfg

Bizzi

**Comment by TimosCodeHub** [comment]
Ich habe gelesen, dass du es aktuell nicht weiter entwickeln kannst und es noch nicht fertig ist - schade sehr schönes Tool. Ich habe auf einem alten Laptop extra Windows 10 installiert, um dieses Tool zu verwenden. Die Sicherungsdatei, die ich in der FRITZ!Box runterladen kann, wird schön thematisch dargestellt - coole Sache. Aber wie speichere ich Änderungen? 
Wenn ich die Konflikt Datei manuell mit dem Windows Editor verändere und unter dem selben Namen speichere /überschreibe, dann erkennt die FRITZ!box diese Datei beim Upload nicht. Daher wollte ich die Live Änderung machen. Die FRITZ!Box wird mir auf dem Startbildschirm des Tools auch angezeigt. Ich kann aber nichts weiter machen. Ist das aktuell einfach da noch nicht implementiert oder muss ich irgendeine Tastenkombination oder Ähnliches verwenden, um live auf die Config zugreifen zu können?

**Comment by Bizarrus** [comment]
Das speichern von Daten funktioniert bisher nicht, da dies etwas aufwändiger ist - Hier muss man die Config-Dateien verschlüsseln und mit Checksummen versehen und das "Backup" wieder packen - So weit war ich bisher noch nicht.

Lediglich das auslesen von Informationen wurde bereits (wahrscheinlich unvollständig) implementiert.
